---
apiVersion: v1
kind: ConfigMap
metadata:
  name: step-certificates-certs
  namespace: small-steps
data:  
  intermediate_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBlzCCAT2gAwIBAgIRAIzJ8078pfW5WfmrZ3+5h+4wCgYIKoZIzj0EAwIwGDEW
    MBQGA1UEAxMNRGVycHkgUm9vdCBDQTAeFw0yMjA1MTkwMjIzMzlaFw0zMjA1MTYw
    MjIzMzlaMBoxGDAWBgNVBAMTD1BpaG9sZSBrM3MgSW50LjBZMBMGByqGSM49AgEG
    CCqGSM49AwEHA0IABIl9PEgFkwfrBHpcyRcgOuocO7un98lztYq9kst/ZFDsM8Th
    k2X/RmaRcFkj3KvLFfGwRhJJ3Kgi9tiQ25NxVG+jZjBkMA4GA1UdDwEB/wQEAwIB
    BjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBRGqY/8HCOyF7G7YJcsxSIb
    FJ3K3TAfBgNVHSMEGDAWgBRIKzZtEO0w/Pix8eLexR8kvDmdWDAKBggqhkjOPQQD
    AgNIADBFAiB08bZOZZkMlDpCnlD/YVQuVrgyyD3r1E6N2q+R6IpYAgIhAMoG4OWv
    cps+iTQgvJX40pKcHSS0HA495+Bd2NkrU0Ij
    -----END CERTIFICATE-----
  root_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBdDCCARqgAwIBAgIRANkYt8S37DW7KItbxVZr9OUwCgYIKoZIzj0EAwIwGDEW
    MBQGA1UEAxMNRGVycHkgUm9vdCBDQTAeFw0yMDEyMzEwMDI1NTNaFw0zMDEyMzEw
    MDI1NTNaMBgxFjAUBgNVBAMTDURlcnB5IFJvb3QgQ0EwWTATBgcqhkjOPQIBBggq
    hkjOPQMBBwNCAATOFoME0It/e323PaeOgrrQZGUGbz3AovjJBBDLAkwld057duoq
    2ppzrcNQYm3/KfFJrGZUbel0PHpIqh4ufFJWo0UwQzAOBgNVHQ8BAf8EBAMCAQYw
    EgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUSCs2bRDtMPz4sfHi3sUfJLw5
    nVgwCgYIKoZIzj0EAwIDSAAwRQIhALmYLFGo9FUAGP6wY8vj1Q5wRXW6n6xV/S6T
    RG/LtMsYAiBwzyJT5Ht+D/KnxHCqhDTxb/kQQL41IyEcswrIdDF4wA==
    -----END CERTIFICATE-----
