---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sn-auth-worker
  namespace: apps
  labels:
    app: sn-auth-worker
    group: standardnotes
    purpose: worker
    sercurity.derpaholic.com: isolated
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sn-auth-worker
  template:
    metadata:
      labels:
        app: sn-auth-worker
        group: standardnotes
        purpose: worker
        sercurity.derpaholic.com: isolated
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values: ["amd64"]
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: group
                  operator: In
                  values:
                    - standardnotes
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      containers:
      - name: sn-auth-worker
        image: standardnotes/auth:1.45.0 # {"$imagepolicy": "flux-system:sn-auth"}
        imagePullPolicy: Always
        command:
        - ./docker/entrypoint.sh
        args:
        - start-worker
        envFrom:
        - configMapRef:
            name: sn-default-env
        - configMapRef:
            name: sn-auth-env
        - secretRef:
            name: sn-secret
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "25m"
            memory: "32Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
