kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: gitea
  namespace: apps
  labels:
    app: gitea
    group: gitea
spec:
  serviceName: "gitea"
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gitea
  updateStrategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitea
        group: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.16.3 # {"$imagepolicy": "flux-system:gitea"}
        envFrom:
        - configMapRef:
            name: gitea-environment
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "250m"
            memory: "516Mi"
        volumeMounts:
        - name: config
          mountPath: /data/gitea/conf/
          readOnly: true
        - name: data
          mountPath: /data/git/
      volumes:
      - name: config
        secret:
          secretName: gitea-app-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 5Gi
