---
apiVersion: v1
kind: ConfigMap
metadata:
  name: step-certificates-certs
  namespace: small-steps
data:  
  intermediate_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBjjCCATSgAwIBAgIQJoAzTYQoGQrO/WNHO8VPdTAKBggqhkjOPQQDAjAYMRYw
    FAYDVQQDEw1EZXJweSBSb290IENBMB4XDTIyMDUxNzIxMzYzNVoXDTMyMDUxNDIx
    MzYzNVowEjEQMA4GA1UEAxMHSzNTIEludDBZMBMGByqGSM49AgEGCCqGSM49AwEH
    A0IABDOhslko8jxgsEqCAzCp8HOhrP1LCL8XEuDMzxWPUGHEyPPuCqs65n5tSFbE
    Q+TAmkkryTXgs1yYZj6fHmCqH5+jZjBkMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMB
    Af8ECDAGAQH/AgEAMB0GA1UdDgQWBBSWevcCFr9RtzTuf6mlj0hCT/6cJjAfBgNV
    HSMEGDAWgBRIKzZtEO0w/Pix8eLexR8kvDmdWDAKBggqhkjOPQQDAgNIADBFAiEA
    /bJBBx4p9Nzgl10wSLGoS2EFmUjMbkOUv+WKR+trq2MCIDHjC7GFFPQMzBGgqs2F
    f4hu/4Ccyu6LmmG40IV8W5YU
    -----END CERTIFICATE-----
  root_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBdDCCARqgAwIBAgIRANkYt8S37DW7KItbxVZr9OUwCgYIKoZIzj0EAwIwGDEW
    MBQGA1UEAxMNRGVycHkgUm9vdCBDQTAeFw0yMDEyMzEwMDI1NTNaFw0zMDEyMzEw
    MDI1NTNaMBgxFjAUBgNVBAMTDURlcnB5IFJvb3QgQ0EwWTATBgcqhkjOPQIBBggq
    hkjOPQMBBwNCAATOFoME0It/e323PaeOgrrQZGUGbz3AovjJBBDLAkwld057duoq
    2ppzrcNQYm3/KfFJrGZUbel0PHpIqh4ufFJWo0UwQzAOBgNVHQ8BAf8EBAMCAQYw
    EgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUSCs2bRDtMPz4sfHi3sUfJLw5
    nVgwCgYIKoZIzj0EAwIDSAAwRQIhALmYLFGo9FUAGP6wY8vj1Q5wRXW6n6xV/S6T
    RG/LtMsYAiBwzyJT5Ht+D/KnxHCqhDTxb/kQQL41IyEcswrIdDF4wA==
    -----END CERTIFICATE-----
