apiVersion: v1
kind: Secret
metadata:
    name: step-certificates-config
    namespace: small-steps
type: Opaque
stringData:
    ca.json: ENC[AES256_GCM,data:luc+svwlBs99SjRqfMSl6/nQwVyEfMBE6pH/Rp8AEIEdmI7fZVNVvqI4orGkyje2BFOvjr9jnj88nGw6XyMkIAgAQJ6MDmI4pwLObtmloLOfxV/LKFVxGLtV5Kh22q8Hl4LlsDFnAnRrI83WSa72uE3la3lB6Dmjxpnp79FpqJfURxwEnHV4rYiQh1o2kO2xXGfSqWEwx/XGZo6/CtSG7fCp1AwsDsNQFSmRu4llfxGlQCa1xbm/J1YQYlZ6cWKydb3dlKpVd7QhinGaA+VqhgU276euBC8lqykIAkRRL5w+zJ3rm0f9Y2gk21jWCglviSrTsIF9aqMTcq6NrPgvlfNpUYnp2BrTX6ZBMjeDm1KeHE+CrSeVdvd2Vz/PRcU+zcKN4fRduRod4fcip1Slld64XpqpVAR/816WX7MIl4xZWV/utyuw/B++VZkh89d59EJcgW9e8kWMEESp5OTdnt3e2TqDrNQZ9eDLN0Kcv3Y6YLqsdTVPWxOF8eUDm8Ge3vrItHNWZzA6TczUqWUgZyKO34C/ggW1DjbILlLHxZa9qsJXDp9xSnuvsRHdMakIfPWqPrqYyFnsYEsKrvTFUTCU9f8CuuW1BPMGSqBvQxNl03tYdm4iYMC/5QIW0vLPt5O4mOvtnyghGSXe8WrF8VmDfJ04jfstER17cTEC7I0uSfAsi5R4CqdqXUTdz4Zhx9TsarWbwm0WsYtbEz0DRfDTEXAfdQUX6jrMybnBHakzZKV/hOamMWne8qLjwr2aBpdB/fRb7URgzRmMHpj+DPOTeOcJYh0AfCXd2WtQAdv4IFjZsM3Wxr6vjwlBpXPcrSx/lSCkbinvFu6MOsga0YhC2WxzBVij0NLyK/SxH4aUInvWjgk4JEwCrzyUiba24MrCcrgVNaJSkNJisk4BCNLhJmag6KKXX5krzzQPYXSbtOmZJx0oC7hah+/m1mrfxm2EEnj2J6KH07H9cU4hHNPyCwsIdSr8Vlo077oJOfXB8n1e517PfcNYappib3v3PX5nwOzO2ZZT86sJs2vKTg0GfKx7XRFKCsfUaS4xAKx2K64nfm1P+jouIXP08JIPvSTSo+1AnlaWFL7ehqLBNuB7GnWB4w4Yozh2sm/C2InYmsocD/hqObK7axpYfpcRYVX6sXf+7f6TvxbRstmqyVG624J/iekb8ShHep9/dAsvtGA4T/z5Rtp2AVAZkFF5vJv/fNUZF0DoQINIw2mpS1Q4QE5HWLuVjFLLR3xjBGsd2mvnzlBVuwXSNOcC+/1mZfMDQnNdqT65BlDskpnxHCfPF5UxzAHhW1M9xyiO2AtN1qsNDmw8nGJRzR4F8RXNKDgFS//Ti3QxEWCfGz7QK6kmNHBjs3SdXCvvvH6NIE5bJ0UJCgIk6W+eEER91N8D/jDyc0343wiMxLndnhXnyZXLmlQrPP5SdP+zH2/CF4jlbGYFeTAqJyxB4S6PIbQe2jk+bImsSgAldUoCBqib3m+2OsHjMgX4/Jz5/aKWKvnaxbjXmPOAa0b6/cJShItTDR6c4aUivFv2jfdGE6Q/lXy6B2RoArbhUMYYIaN4VjAhzTsiDc0LoML7+t0dfjHe9uiQCjGppIPEdxMMb9dNRvFGw/+KmXGX9kJ1xKWO7gfCKIFYs4PV1oaWYHK0zrUuN9QKrUBY7W9meOGS/Dxcy2qzIoMBKDQvfplkKoX/1NniSGq4DVEHvKEQORsmmGw9DV77sgT+34KgM1NMQ086tsAuVTv5zl1sP4DBcHnGQQB9h3kwHvhmx2kzRoqUsYMTUySmDlyUiFLQexreHmOgauHxZ5JQYIiHajRzKS/nw1BmIxhC3/+6+p53oLIcEb/KAs/yHml5Lqi5KEr48c/JW+frEMBamFurJpEQ/Wt7b6YlScdoFDYvMp2+/8OuXnE+afXEAWy7eF2yG6j2iAu6RLMIqiufM5slrcMoE7fCbzPSbz2lMCKMm7qVfbBX+OOzwdMJ9mNNY8oAyCI7qyRkTt7zwcgyGJLNnzsgu2X3qoXaUB4GZ2Rrw3/3ykQmMuKFRo1VJADhIs0IVA1qIwPDHETsX7oV58XmBRBGV9eU8kAOK/+33xRrpWNX/VypaDcw+t8ttxzWqBcKXSeTHB56Y78iH05TefiCHlwSE0RLuPe4UCJ29CWZhsiUXCnddQ4ynbBX2tr4MoZrf0VG5N64oxng2dfbazAmeM1N8RL1+gFzTWOj2LQ2jcgEs/givRbhV0hHGCqMNuBwSDVy4wsgFVLvVtQJLfjeER8o+/jeTtu/4CUTux1DK3FMzcoautQS4QjAhtRraIC1ZubskHdQwZGrYXi9K4O4DygQyzc53Jx2nuaWMeNlu7IxF+SeEid5dSZZpZinfpWtEG24gXwgmU9hl1m4uz+r8IfZcQhFvHmFWSJjtsp3o3AS1K9CQHk6tyddIMFisEJedP1ASCujxSjXmGfAgjaCmPdG2sgOSpbo/z3cr+8C8Xp2HxL3VTiWVbb/tjoqtljTDIMXkxdNO2QLfVApqTv1BRFtpEcyxIJldDJm382tZ3kifojpk7gr24lZoMz+Fc0JAl7lNJ+Xv9KZ+tcZvJZpK8hEAuODALHNce2noZU8Mkdhp7puoSMKLtVZ7n4b0WKR/gZ8eYyQcRprgOIRpoS2QkUkvbEuUQdAVxfKGPWO5kMTVsLfmfNDLHKhel4ApnU4kQoz9smU+uLUhYrBzVWPl64QLJT7yqJpcjxz,iv:Hn1XQEF+iWuCISU3aZEAROq4JPK9cnC1+8L5oAOhueE=,tag:OdfNQVWcTVs+AM8EQPby9w==,type:str]
    defaults.json: ENC[AES256_GCM,data:IAuEkYFCGqQGmZJR04w1e76gVrKdHKfraL/g4gXHHH5KFi4l215fjEbbMtj8pJewIgLdVvUzBuLw5CgRoNmfcYhotOKafqT0Qfba5bVEPSzfMcifwoMq/4c251e94IYodYaI0sLf4jOpLMePOQvl9k1yhRqIQfi1nM+EfX7QzFY7OYWA5uLpYYlStzTcC6v75CaCQON8pQneiQM8d8QDoymGQeaUifBypyVC8T6S6aI6HwnI4AVgJ71u3JM9DkERHVAbMAVe9DsoaGnjn5L2bA6Hkhdxkq+5HYzxS7SqNaKXTPVq/R+tC8z8Orwp4pByea29aO4=,iv:Z88kEcMn2kb15N7EKtZ/Sb0Ckec684QfMpqKUeaDQxo=,tag:rNFGI85oSjnnQ1LtD+4Wcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-03T18:05:13Z"
    mac: ENC[AES256_GCM,data:LRAyhMJJRE2Sh0i9B0oasrsLqZ7ihDSvWG3hAoKOVMt6fTwbOGKweT0TKBS4gF9d7076QjMLsq6AVywxYqEiil+chG9YmkTI9Z7T/usNqEruZxIuXdsqXLOQ7nidxbPmAaGi3y5vjF3hQWYZEyUNodAp0KwtB3njy/Rco9wqEl4=,iv:lmXq2+367pSy5of1Ad51E4CLYNJ0ZMu/ib9Fp1NtX8c=,tag:DwFxIBZHg0+kkT7zGDOq+g==,type:str]
    pgp:
        - created_at: "2022-08-03T18:05:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyV9b1w7rilCARAAr+rx3vfwYe3SM296JRFPjozIg8UH+x21ai1cPGj5eEVX
            lJR79IiHhgTHP3mh8UeNvG97BEctFLLz9egeqNXk1xKdHbUwvEkKnNr586FkI3Dg
            Ki9JDkBzoDkyh6z4R0uic9XAqe6ucAeslkCQ7iEhXNFR8XhkBCxWWRqAiAd9W+gl
            CvId//X54N+iJ9hFcsx4H4gQuKXGbp18DxbqC/xzPyPsMxWnzzIrLpW3CTdHfGRD
            GE8YDYZS04kwDCOcB9m/KcdA6Y+CBPq0TV3Ow6dEOFKLl0wUZr5RkrOuCMwCNnJj
            JF4l1PI6BF9gHmu1whbJOz3wmxi6Z0qo4sDBqtbW2tAtCYbP3oUAT5AFL49ns8b6
            bMjJ/cd24wNWnzx0ECbK7ye08PIf1ThEAKNZI/Yrf4oi42bmj8YstaV3m/icLVmw
            VqaL69OSrDEGcDwrVN/HMLaYUrO3Sa7Ge+7Lz9nxjz3eG87K9iyYmpKHsMJXJbQ8
            Ap/Nmd3zeQupYjwAwK4dcMuvzlPbo7UsHytJl08kiK48P5gMvrqTJf0JfrB5lphx
            pHtAqjiQznWrJY+OMhJqihbMIUFnKDy4N0KOo2vMlBN2Asl6vQ6wwK0NfqFqtNtl
            9fDFwjs7MdjFDk9ZxQHre2uLbqTGxITpvIbItuzkmNCRqZ+Kyu+/c2y9f0i6o8LS
            XAFwL2rZ+1kygJbJfhPaah0w/lVL8ewl1sK6f7jqRS43h7BZK539IPNPz6hecBX1
            aA5hy2H6BWY/87EceBGZxAdGEdb2/imlKtywbUVTktQheDQacjzIWCEzSrDD
            =JU2W
            -----END PGP MESSAGE-----
          fp: 9B943C63F470C6AEF51D02E51966026E6BC4FA59
        - created_at: "2022-08-03T18:05:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DV/s3aZyXgOMSAQdA+adMlCMoKjqmy0wQ4Q26VYErINynjVQ66AzLDY1HPiEw
            xko3Sdp5hbp9RjqJ25DDnVHA+MeaKfLNixT0YyGblDxE9se3oGsDi7R5LtSlkxIg
            0lwB39m9g5Y7BlFFpzsW81uaTjmDMzl87y231kZlZWy02KnWjubGHhp2CLLLjfhe
            x8lxvjeqWOM5IT836jQeJmdLqOY4p9xEJ9y0i41sFCpVb1d6OkIDcPfKlmQS5Q==
            =+0GX
            -----END PGP MESSAGE-----
          fp: 71DADA7922B3E08101B3341369C476704F97DBDA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
