---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: ingress
  labels:
    group: cloudflare
data:
  config.yaml: |
    tunnel: kub
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: "*.derpaholic.com"
      service: https://traefik.ingress.svc.cluster.local:443
      originRequest:
        originServerName: "*.derpaholic.com"
    - hostname: "*.conlon.dev"
      service: https://traefik.ingress.svc.cluster.local:443
      originRequest:
        originServerName: "*.conlon.dev"
    - service: http_status:404
