apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: routes
stringData:
    users: ENC[AES256_GCM,data:icrm23Jdgy4lbXPxc0Rz5e0Evv/yhh2etwJwkYbp2UqtRmgziZWd0d666dEtUrLOn/SmKN/7Y2z1Eptb4w==,iv:PQe3v+u+te4ELTEcPcUs/p4K0irDCE+H1ZRqF6uCLBY=,tag:kNn8z1WcqD9qzfLC8i0PNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-03T18:05:15Z"
    mac: ENC[AES256_GCM,data:dAfc4FbRJQxcoPGTbg8OG8kCwBPN31XRuLU3DgnB8yl6w4ZKJ5LVZ5sJyR0leZ4FuVKTDXs3XIgQgJ8HkxSw9/eguCRCzczbCLHdhr0jpD/oEjVKmWCp/NI2ke9SF3k2bPYsgp76z48NhQK7sJ0mOitHGhC8EzwYVGD9Ugmjj6Y=,iv:YTmwEZY6clsP+VwLSOl9ZnGsgKHKaxAi2AYigYXWTks=,tag:FPeDhTIEmp+kXctz/Tffmg==,type:str]
    pgp:
        - created_at: "2022-08-03T18:05:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyV9b1w7rilCARAAqcstkYXPCtGc4HgL+eZMdFPbKc9gyseCJnIhp7WSJeEk
            zYxIjNj1LVkyEVNf562ICZ5UzNYtoG0GntgdCsdyu66a0MPGDZFfhAPUA37Mygef
            ALN9gE6FKVN5TrDI6VzE9ofUnn7XNJKLtnWuvI3me3X89uSIZrOZOawIXNlE80Bb
            SWTkQL5TjKqDYkd19ajAdwB3vINrk/K9Nf+R6+1EB8pKE2BaY9N13skHf9NuYP4m
            I/HF2wFLvQhEpBPJL7rfjlK83r05Bh6kjV/JSrm+jfqDX8I05JBSZAMkfTXh3bmt
            NjBKjtEvQQdBr5whPjrElbcIrzWNcl3iZRHWOxuJE6tAyDzURf/DbLVc9iyTt2r9
            dtVl8el3IIitQsBP84BbXsFV4rp+P1YNRcOUOBAwWqWWOP0HBnko0J1PlFEAH7jl
            KyU30i370UZrvNlxW3+G7NN+o38JLE/d7eoGbRDhQT60f1hJtfSXKB2XowUniZBf
            DJUiXNlAObT9cjh2uiaPBvn+/b4jLZrLmDoFg6Hnc/fz9DZWdu0N0xBK3Ebj62n6
            jKq03nhIegkgh/uI6lGRrq0W2THljpw8DkGIx6TyaQtBqVuR5HGDk6N38QEDw7aH
            8IrVZoL99IgoL7JVZkKdnHp1wwJzi1vOCBCxVYNs60YoanTobd/7lMK+9TEuf0HS
            XgFM0m+Y3K7uYK5YvAeUmP4zKVyIKYgeJxESpLbXrrawxMbeNOAx0wMj74MCgFmP
            3S0/K+1HQx1T6cCUgmRzMwVJNFJW0JgnjDtGqL47np4lxUdXcfMKsK9yXvxj4IU=
            =r6Hs
            -----END PGP MESSAGE-----
          fp: 9B943C63F470C6AEF51D02E51966026E6BC4FA59
        - created_at: "2022-08-03T18:05:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DV/s3aZyXgOMSAQdA9xEwLR3ijUTAODi8JL19pcoRAD5kC/5t4rMST+95eBEw
            JKkcIenFTvpeJMWtTF5z9xTmpAroVs1kW1IOGPUfeB5fvWukDfIBwrg0y5T1k55j
            0l4BcaNlkgt7Sqwi1/BN6aSdFTk5vTaAwDm1usjGCJc9HwostKugtBNLtklY8m6D
            VXrGDGMCUgmCpeB3iAS88Wclj+YlBlVZZUdwcgIxVcoKRf0kkkuavwOmeAb+wGAd
            =U3ZZ
            -----END PGP MESSAGE-----
          fp: 71DADA7922B3E08101B3341369C476704F97DBDA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
