---
apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: routes
data:
    users: ENC[AES256_GCM,data:dXEX660XlgccxdbGwM5jHnZxQ9r+ONpBEigiN/vqMJpS4bx3MESJGXiGQQbZhpuQxS6HKe+sH8jvZoUgJQ==,iv:qBlQi3/tVc5FYZlRUYFBekmhiH8m4DRJQzJtXVLgx9s=,tag:6i9n92yMkCtstHTmbrP+Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-05T00:37:33Z"
    mac: ENC[AES256_GCM,data:5XoBLdHl8BKFpkiefUlFVIErjKq8MECHkuL6PfJ5Vb+eIjvTIKrOuSjGUFA+EjRRkZiX6ggejxqwFAeJBbo/9zS82dwCw1js2ZCztDksht27nGfrDQVC2Ly2FxN6tRqgjw6Hw3yOwCqFAIwGsdh2Y4r6tZ0JiDm4OckIZM6v/1Q=,iv:rLFQsW42RwwEawFW2Bjs42oaXgIOMdX8xbfBw/V87sA=,tag:Vkpx/tPKDxWTw9oeJf3LLA==,type:str]
    pgp:
        - created_at: "2022-03-05T00:37:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyV9b1w7rilCAQ//euqMoLgYGKEG8fSqO6swf0ebcoZa0nsWzzukN+4JdmtI
            UOcQCGhaW217qVjIYv7yUYkCfv6bvtCOSb/VysCbkKaFKZZLb+Awdy4QEVjq30QQ
            Cm+MfLJqSzr8nzt91st/xlI0s0GzIk1Q7wf9ifjlpWiv494BR7dsh9hhjDsntUgo
            9gvjs1IGC6l1cchbOVkJcBMiJInAdSlPTSg0POuJA3VSC50+2zwJET6Xw7OKjsL2
            tV7Z1UTtBBTHMMMXWwPWiit20LuBowJ/ovvyS9pxPFAmBULUOd57+4G4VZPAgfMj
            7YJckWGzDConPC4ERs7SrP+n04tXrmDKjBx/yVVutOKygEcQWjOFBnQMwCNe4X0z
            MJ7prJqjwiOCXwSaHUtL8v+oqXGbZYrcyVjWS7VkrmS4Ohze/sHJG70gNgegauIX
            u9Az9KvSYgRNGFRsCkoASzGVZpqhqRGY9dWl3i28qDRmcnq0ZhUa2xOCry0Ct+13
            pnU3FinyQbC+F1J6oSsH1gkQtDAvyvaSQNvZOw0terX70oOiaEJIRwXxgJ57dMNi
            XlhBL8KJe4v6+laWosL2ma50uc2AP7WeG1U7SBOgwCW/3u7sYoy4iMOYjGRCaACz
            rF3hFm7ZcILH32UjmKh6YV4RFn+OKycz1pcxnhh0GXZd5KQHS5xYeUXVlFuX6lXS
            XgHrwj105YrejythlgEbeKmavNrmzWy88YLtKu/61+SPz2nzgngMnr+QwFDP8ofy
            /1kbpP5KCL7LyEEq2UQbU797aRCsccXXwd4PzLeS27oqPCuSMxMM1vvRIkfBLYg=
            =9VED
            -----END PGP MESSAGE-----
          fp: 9B943C63F470C6AEF51D02E51966026E6BC4FA59
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
