---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  image: traefik
  interval: 60m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: traefik
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: traefik
  policy:
    semver:
      range: 2.x