apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flame
  namespace: apps
  annotations:
    # set ingress controller
    ingressClassName: "traefik"
    # default settings for traefik
    traefik.ingress.kubernetes.io/router.middlewares: "routes-default-header@kubernetescrd"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    # sticky session for traefik
  labels:
    groups: dashboard
spec:
  defaultBackend:
    service:
      name: flame-dash
      port:
        name: web
  rules:
  - host: derpaholic.com
    http:
      paths:
      - backend:
          service:
            name: flame-dash
            port:
              name: web
        path: /
        pathType: Prefix
  tls:
  - secretName: tls-cert-derpaholic-com
