---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ff-sync-auth-config
  namespace: apps
  labels:
    group: ff-sync
data:  
  TZ: "America/New_York"
  FF_SYNCSERVER_ACCESSLOG: "true"
  FF_SYNCSERVER_LOGLEVEL: "info"
  FF_SYNCSERVER_PUBLIC_URL: "https://sync.derpaholic.com:443"
  FF_SYNCSERVER_ALLOW_NEW_USERS: "true"
  FF_SYNCSERVER_FORCE_WSGI_ENVIRON: "true"
  FF_SYNCSERVER_FORWARDED_ALLOW_IPS: "*"
