---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ff-sync-auth
  namespace: apps
  labels:
    app: ff-sync-auth
    groups: ff-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-sync-auth
  template:
    metadata:
      labels:
        app: ff-sync-auth
        group: ff-sync
    spec:
      containers:
      - name: auth
        image:  ghcr.io/crazy-max/firefox-syncserver:edge
        envFrom:
          - configMapRef:
              name: ff-sync-auth-config
          - secretRef:
              name: ff-sync-auth-secret
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "25m"
            memory: "32Mi"  
      dnsPolicy: ClusterFirst
      restartPolicy: Always
