---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: xbrowser-api
  namespace: apps
  labels:
    app: xbs-api
    group: xbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xbs-api
  template:
    metadata:
      labels:
        app: xbs-api
        group: xbs
    spec:
      containers:
      - name: xbs-api-pod
        image: tetricz/xbs-api:latest # {"$imagepolicy": "flux-system:xbs"}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "25m"
            memory: "32Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        secret:
          secretName: xbs-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
