---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: adminer
  namespace: apps
  labels:
    app: adminer
    group: db-clients
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer-app
  template:
    metadata:
      labels:
        app: adminer-app
        group: db-clients
    spec:
      containers:
      - name: adminer-pod
        image: adminer
        imagePullPolicy: IfNotPresent
        env:
        - name: ADMINER_DEFAULT_SERVER
          value: "database.ingress.svc.cluster.local"
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "25m"
            memory: "32Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always