---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminer
  namespace: apps
  annotations:
    # set ingress controller
    ingressClassName: "traefik"
    # default settings for traefik
    traefik.ingress.kubernetes.io/router.middlewares: "routes-default-header@kubernetescrd"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    # sticky session for traefik
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "cookies"
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
    # flame dashboard stuff
    flame.pawelmalak/type: "app"
    flame.pawelmalak/name: "Adminer"
    flame.pawelmalak/url: "https://adminer.derpaholic.com"
    flame.pawelmalak/icon: "database-search" # optional, default is "kubernetes"
  labels:
    group: db-clients
spec:
  defaultBackend:
    service:
      name: adminer-svc
      port:
        name: web
  rules:
  - host: adminer.derpaholic.com
    http:
      paths:
      - backend:
          service:
            name: adminer-svc
            port:
              name: web
        path: /
        pathType: Prefix
  tls:
  - secretName: tls-cert-derpaholic-com