apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: routes
data:
    users: ENC[AES256_GCM,data:MdiBCyzq6NTvQLOQmbs28+pn+idsyXo2ccRcRDXva7mOOi6mokxzzIclIewWV9gnUe4JuQ16zpLzhx8q/g==,iv:krB/I8QBLO7x7tjJgv45upYW2BWhXM7hU2Q4eBeO3Mg=,tag:e9J8jMjQV1EVB+bfYU21eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-17T21:32:41Z"
    mac: ENC[AES256_GCM,data:kGpwUEe/is3almZnwtLiJ0BY/3k85a0yc2waJ709ITD4w37AV05vTy3p2HTWYYNqy1UEpUUHlpizvqELEzUMt82DGcscBXCeDHGzUi90BsLIPxi7jGyhP0pQSD0NJP6P2kMGPmX7fBp/A3v0L35AAFHIWLrL4n7dTf2xjcH1zXs=,iv:+DSM5mfmF7R+JOAIfZvTqZToioimMjIp6ep0/Ypct8g=,tag:oCBAUY4kie/czTojc7aEGw==,type:str]
    pgp:
        - created_at: "2022-03-17T21:32:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8HJM/S6WGi8ARAAk/dKWRLYBpHX2V9U6qXAyoIiPgCOrqcroOz2QPkI6DFE
            w6JgpmUnvM/HYzx/rCTDpMXva5EO4amAZF8SnjFgwHGEfhdmeu5fZZQ40WjKhePA
            2tUowjRIr2xJupXcImlbfIZTUXp9s93JpneVruL8FZX9exapx8Bu9r5L6v15T0YA
            JScApt4qGZvJ4vWUXoNxyvVvnbvHoUldXfH7GcUp99znYCRQ9YYkjK1uAGQn+uH7
            e6u0cT2Kt11PxzT+MiiFMt1BzbQct4otknqrqJYMtl0BRru62QVAV9FB4DfTDxkH
            BZ3d2tcvaATLWj0Dzif4k05yOf8zXHTSEz9sGJF5WvRyDTdpQYSf58m3Q3vNiAQi
            HvrOQpO2aLen9WdH24uERMu/qwtYFQYoIIGLerRQ8zZj1rSS0+OgdZLLBGa/3T5y
            h4K0b1qY+JaPU9P4/bKQJHqxOWpTT4jzDhvvTLR2Jo9CZOL2m1FefORQo9wuy0Nf
            Z+prRnfkwVsKrN/421xV9HtCbzLZQ50o97tOe+j5HaodoIcdt5b7AabarZ+YE691
            csNsHrvhr+dopnBqaGkI2yHsSWQln0AVMWJV3is2tRaiWJM7pa6pWGyv14mecGjv
            px4NKmE/1XnNUrJzndUpeJkIdPhq5im8XGw6xxSJnNjxy7jOD0MhiBgzQ5c0G9XU
            aAEJAhBBKO0IEYEkroo4/YEUerdFcIMFZjCNl+PBCKxQcFu0ecRD0G45Aft0H8Bm
            KYepdOZI5N/kIv7XOyU5OIDAtJoMMf/5iQ1Vt9iwa2JiyOTxena0luCXmeukTyAL
            SD73HEdBFqUX
            =6Emc
            -----END PGP MESSAGE-----
          fp: 412ECB5B783A4731BED1F2F8986B9B5121BCBFFD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
