apiVersion: v1
kind: Secret
metadata:
    name: traefik-dashboard-auth
    namespace: routes
data:
    users: ENC[AES256_GCM,data:OXObrNQVHL2yxRxeSF5i9zq4rgVIFDZYEIguPPa8bx4WvZdmklB40ykr4SvoCb8Zm2rvC6qcojG+byrOjg==,iv:AEotmoop4V2mVUV+JO7L2adlqTRRFpx4Vw8Babx7s60=,tag:0/fNH+u/f1P/+aC9P0L03w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-07T01:41:08Z"
    mac: ENC[AES256_GCM,data:XBgUAmLHn+53lLIf/JFDGYwggWRzvH33HLHqEZnHhXKy7CHIJWgBaTHjGYJrGjbiLohJEt9ud4VhjuGjID2VEd28Qx6GEPIi5sglejkNpUtR5RTTyjSgGQAGzy8zK2hylRy7t9jTQ12jm+M3oldWYgQsI8O8aJSz9Ce7YY3JiC8=,iv:7l6cOHt4Sclk5FHF8cpryqCV11SZd4g2G4AE8BnIfhI=,tag:bUhQ7e+4SkYQfFgThAeWcg==,type:str]
    pgp:
        - created_at: "2022-03-07T01:41:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7YWJ9fa/MY+AQ//XYAkpDH/FI0PucbzuimMDF3y9IIF93zRQxDnR8uBHI6v
            ZVnBxniAbsbCtFxE9mnDXGm7EKQ9uPRrxIJMzavUGpwj425tlR8qFyfd0aYhCFka
            9Uc2H9e0wNgClOabbT88679hDgy46EsRB0vkMQi4hQYRlw+f9MsQ0U+wCFTeWV0H
            ShPtK67jO9PZGjaBGA2JMKXhNd5+C0AO6IVPMHkCohOnDv219XmYDgYhv9CD9XUM
            uWrgfpvTQ2MD47a2yFXOZ499Dh/4p9SZtuqx5uWQ+xm2BtePBBPMSsEz0tKbZUUg
            v/5IdPT/TPNqgxDZHFQlZomHJxrI7TayrXH/IyX+3wRXON7HToyFhhcFKaFQ6XLp
            L2T8LjBSmiFTk9iTLApnYP3wPdFHnKYMPBn9ggyiRH9RzP1Yb1McxVqo0aMu6BLg
            sjyqc0I6XtKhhnXAReLoipZDs3qVwEDkprUyPr0eMnrFRzt87p1ASUCIloYexGDg
            2MFB/7ZnWa/cXTqvwWJaKRBto+gskjoKWE7m74fBOz1AYz3qPr/O5e8x+zYZjR0f
            Fe7FZP247S77oO+g2SZ4qfnOy/s94QkuDC+eOc3Crb/fatCXW5mpQZ2ZJHmmi3d5
            WPVIDZ1FsUk/DT8T4rdOWa437UMaUg1+9+6In040gX5y7RuEiZRkFlatFvgx8FHS
            XgHDQhM1T8sE+bv7uPZDZgMpebAEr5UHO02zihUNhbqiAW4WWPkdoCGd8R2p9nei
            uRHsQAXE/jGtb81KCUSuAr79JpNnBiRxob+HDHwFveP/8XvkEmZQNJMTELhwrsk=
            =kL5U
            -----END PGP MESSAGE-----
          fp: 5893FC939E4E25F521347FECCD0000CE76689A55
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
