---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: root-web
  namespace: apps
  labels:
    app: root-web
    groups: root-web
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: root-web
  template:
    metadata:
      labels:
        app: root-web
        group: root-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: root-web
      containers:
      - name: website
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "25m"
            memory: "32Mi"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: root-website-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
