---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: apps
  annotations:
    ingressClassName: "traefik"
    traefik.ingress.kubernetes.io/router.middlewares: "routes-default-header@kubernetescrd, routes-pihole-add@kubernetescrd"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    group: pihole
spec:
  defaultBackend:
    service:
      name: pihole
      port:
        number: 80
  rules:
  - host: pihole.adrp.xyz
    http:
      paths:
      - backend:
          service:
            name: pihole
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - secretName: tls-cert-adrp-xyz