---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: some-app
  namespace: apps
  labels:
    app: some-app
    groups: blah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: some-app
  template:
    metadata:
      labels:
        app: some-app
        group: blah
    spec:
      containers:
      - name: some-pod
        image: ckulka/baikal:nginx
#        command:
#          -
#        args:
#          -
#        envFrom:
#          - configMapRef:
#              name: special-config
#        env:
#          - name: MESSAGE
#            value: "hello world"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "25m"
            memory: "32Mi"
        volumeMounts:
        - name: some-pvc
          mountPath: /pvc
        - name: some-config
          mountPath: /config
        - name: some-secret
          mountPath: /secret
      volumes:
      - name: some-pvc
        persistentVolumeClaim:
          claimName: some-pvc
      - name: some-secret:
        secret:
          secretName: secret
      - name: some-config
        configMap:
          name: config
          items:
          - key: config.yaml
            path: config.yaml
      nodeSelector:
        location.derpaholic.com: "newport_news"        
      dnsPolicy: ClusterFirst
      restartPolicy: Always
