---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: step
  namespace: ingress
spec:
  secretName: tls-cert-step
  privateKey:
    rotationPolicy: Always
  ipAddresses:
    - 10.2.25.150
    - 10.2.25.151
  issuerRef:
    name: step-issuer-2
    kind: StepClusterIssuer
    group: certmanager.step.sm
