---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conlon-link-config
  namespace: apps
  labels:
    group: website
data:
  META_TITLE: "Allen Conlon"
  META_DESCRIPTION: "Allen Conlon Link Page"
  META_AUTHOR: "Allen Conlon"
  LANG: "en"
  META_INDEX_STATUS: "all"
  THEME: "Dark"
  FAVICON_URL: "https://avatars.githubusercontent.com/u/1966320?v=4"
  AVATAR_URL: "https://avatars.githubusercontent.com/u/1966320?v=4"
  AVATAR_2X_URL: "https://avatars.githubusercontent.com/u/1966320?v=4"
  AVATAR_ALT: "Allen Conlon Profile Pic"
  NAME: "Allen Conlon"
  BIO: "Inspiring Sys-admin"
  FOOTER: "Thank you stopping by! This website is in a Kubernetes Cluster in Oracle's Cloud"
  GITHUB: "https://github.com/a1994sc"
  LINKED_IN: "https://www.linkedin.com/in/allen-conlon-6b920553/"
  EMAIL: "Allen@conlon.dev"
  EMAIL_TEXT: "Feel free to email me"
#  EMAIL_ALT: "allen@conlon.dev"
#  EMAIL_ALT_TEXT: "Feel free to email me"
#  GITLAB: "https://git.derpaholic.com/"
