---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: conlon-links
  namespace: apps
  labels:
    app: conlon-links-api
    group: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conlon-links-api
  template:
    metadata:
      labels:
        app: conlon-links-api
        group: website
    spec:
      containers:
      - name: conlon-links-api
        image: ghcr.io/techno-tim/littlelink-server:latest
        envFrom:
        - configMapRef:
            name: conlon-link-config
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "25m"
            memory: "32Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
