---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sn-sync-worker
  namespace: apps
  labels:
    app: sn-sync-worker
    group: standardnotes
    purpose: worker
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sn-sync-worker
  template:
    metadata:
      labels:
        app: sn-sync-worker
        group: standardnotes
        purpose: worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values: ["amd64"]
      containers:
      - name: sn-sync-worker
        image: standardnotes/syncing-server-js:1.51.0 # {"$imagepolicy": "flux-system:sn-sync"}
        imagePullPolicy: Always
        command:
        - ./docker/entrypoint.sh
        args:
        - start-worker
        envFrom:
        - configMapRef:
            name: sn-default-env
        - secretRef:
            name: sn-secret
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "25m"
            memory: "32Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
